version: 2.1

commands:
  run-npm-test:
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package-lock.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package-lock.json" }}
      # run tests!
      - run: npm run lint
jobs:
  node-v6:
    docker:
      - image: circleci/node:6@sha256:4a6f6140060e97c54279e75a79c681b91b164f0cd8db21267807ecbf18e87a0e
    steps:
      - run-npm-test
  node-v8:
    docker:
      - image: circleci/node:8@sha256:8457a32a9ce3f83272d0b528bf7ceb3dd39011251f8899df8a4c7c8aef76725a
    steps:
      - run-npm-test
  node-v10:
    docker:
      - image: circleci/node:10@sha256:e8c5c65dad1ebfeae87fad63a8d1293b6fa8cd5aeebe50fa0d9ed8d2c63e99cb
    steps:
      - run-npm-test
workflows:
  multiple_builds:
    jobs:
      - node-v6
      - node-v8
      - node-v10
